### ISSUE TITLE
i18n dynamic page routes not showing on sitemap

### ISSUE THREAD

**Issue by lisaschumann** [harlan-zw/nuxt-simple-sitemap#48] opened 2023-05-15 09:05 UTC
### Details

I have set up my build with two languages (English and German) and I am struggling to generate the dynamic routes in the sitemap for each page as "/en/{pagename}" and "/de/{pagename}" or for the blog posts as "/en/blog/{blogpostname}" and "/de/blog/{blogpostname}" respectively. They are not coming through on the sitemap, and I feel like I miss something on the basic set-up or understanding, that is preventing them from coming through.

I made a reproduction here: https://stackblitz.com/edit/nuxt-starter-uhq2jp?file=nuxt.config.ts
The blog posts are being fetched from contentful, but in the reproduction I am just using the data array to keep it simple. 

Really appreciate any help or perhaps there is already an existing example version online.

Greetings from Germany!

**Comment by harlan-zw** [comment] 2023-05-20 17:07
Thank you for the reproduction @lisaschumann! Sorry for the delay in response, currently traveling. 

I will try and look at this when possible.

**Comment by lisaschumann** [comment] 2023-05-31 14:06
#61 seems to be the one probably solving my issue here:)

**Comment by harlan-zw** [comment] 2023-07-06 05:16
Will close this as a duplicate of https://github.com/harlan-zw/nuxt-simple-sitemap/issues/61

**Closed by harlan-zw** 2023-07-06 05:16 UTC
